export const meals = [
  {
    id: 1,
    name: 'Breakfast 1',
    description: 'Description 1',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 100,
      fats: 10,
      proteins: 10,
    },
    category: 'Breakfast',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 2,
    name: 'Breakfast 2',
    description: 'Description 2',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 250,
      fats: 15,
      proteins: 34,
    },
    category: 'Breakfast',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 3,
    name: 'Breakfast 3',
    description: 'Description 3',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 230,
      fats: 8.4,
      proteins: 27.5,
    },
    category: 'Breakfast',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 4,
    name: 'Breakfast 4',
    description: 'Description 4',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 190,
      fats: 8,
      proteins: 15,
    },
    category: 'Breakfast',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
    {
    id: 5,
    name: 'Lunch 1',
    description: 'Description 1',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 100,
      fats: 10,
      proteins: 10,
    },
    category: 'Lunch',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 6,
    name: 'Lunch 2',
    description: 'Description 2',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 250,
      fats: 15,
      proteins: 34,
    },
    category: 'Lunch',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 7,
    name: 'Lunch 3',
    description: 'Description 3',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 230,
      fats: 8.4,
      proteins: 27.5,
    },
    category: 'Lunch',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 8,
    name: 'Lunch 4',
    description: 'Description 4',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 190,
      fats: 8,
      proteins: 15,
    },
    category: 'Lunch',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
    {
    id: 9,
    name: 'Dinner 1',
    description: 'Description 1',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 100,
      fats: 10,
      proteins: 10,
    },
    category: 'Dinner',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 10,
    name: 'Dinner 2',
    description: 'Description 2',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 250,
      fats: 15,
      proteins: 34,
    },
    category: 'Dinner',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 11,
    name: 'Dinner 3',
    description: 'Description 3',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 230,
      fats: 8.4,
      proteins: 27.5,
    },
    category: 'Dinner',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 12,
    name: 'Dinner 4',
    description: 'Description 4',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 190,
      fats: 8,
      proteins: 15,
    },
    category: 'Dinner',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
    {
    id: 13,
    name: 'Snack 1',
    description: 'Description 1',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 100,
      fats: 10,
      proteins: 10,
    },
    category: 'Snack',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 14,
    name: 'Snack 2',
    description: 'Description 2',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 250,
      fats: 15,
      proteins: 34,
    },
    category: 'Snack',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 15,
    name: 'Snack 3',
    description: 'Description 3',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 230,
      fats: 8.4,
      proteins: 27.5,
    },
    category: 'Snack',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 16,
    name: 'Snack 4',
    description: 'Description 4',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 190,
      fats: 8,
      proteins: 15,
    },
    category: 'Snack',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
    {
    id: 17,
    name: 'Drinks 1',
    description: 'Description 1',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 100,
      fats: 10,
      proteins: 10,
    },
    category: 'Drinks',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 18,
    name: 'Drinks 2',
    description: 'Description 2',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 250,
      fats: 15,
      proteins: 34,
    },
    category: 'Drinks',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 19,
    name: 'Drinks 3',
    description: 'Description 3',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 230,
      fats: 8.4,
      proteins: 27.5,
    },
    category: 'Drinks',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
  {
    id: 20,
    name: 'Drinks 4',
    description: 'Description 4',
    price: 10,
    image: '/salmon.png',
    nutritions: {
      calories: 190,
      fats: 8,
      proteins: 15,
    },
    category: 'Drinks',
    vegan: false,
    vegetarian: true,
    glutenFree: true,
  },
]
