import type { NextPage } from 'next'
import Head from 'next/head'
import Header from 'src/components/header/Header'
import About from 'src/components/homepage/about/About'
import Hero from 'src/components/homepage/hero/Hero'
import Menu from 'src/components/homepage/menu/Menu'
import Media from 'src/components/homepage/media/Media'
import HowItWorks from 'src/components/homepage/how_it_works/HowItWorks'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Hero />
      <About />
      <Menu />
      <Media />
      <HowItWorks />
    </div>
  )
}

export default Home
